project:
  type: website
website:
  title: "FIG — Farm In Grid"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Org
        href: org.qmd
      - text: Trace
        href: trace.qmd
format:
  html:
    theme: cosmo
    css: styles.css
